import { cn } from '@/lib/utils';

/**
 * The Steerpost mark: a path leaves flat, bends up in two equal turns and lands in a paper-plane tip.
 * Geometry is shared with `public/brand/mark.svg` (generated by `site/scripts/build-brand.mjs`); change both together.
 * It uses currentColor, so `text-accent` gives the brand colour and `text-foreground` the mono one.
 */
export function LogoMark({ className, animate = false }: { className?: string; animate?: boolean }) {
  return (
    <svg viewBox="0 0 64 64" aria-hidden="true" focusable="false" className={cn('h-6 w-6 shrink-0', animate && 'logo-draw', className)}>
      <path
        className="logo-path"
        pathLength={1}
        d="M7 53.5H19A12 12 0 0 0 31 41.5V33.5A12 12 0 0 1 43 21.5H46"
        fill="none"
        stroke="currentColor"
        strokeWidth="6.5"
        strokeLinecap="round"
      />
      <path className="logo-tip" d="M42 8.5 59 21.5 42 34.5 46 21.5Z" fill="currentColor" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" />
    </svg>
  );
}

/** Mark plus the name. The name is live text (Inter, semibold), so it follows the page font and stays selectable. */
export function Logo({ className, animate = false }: { className?: string; animate?: boolean }) {
  return (
    <span className={cn('inline-flex items-center gap-2 text-foreground', className)}>
      <LogoMark animate={animate} className="text-accent" />
      <span className="text-[0.9375rem] font-semibold leading-none tracking-[-0.02em]">Steerpost</span>
    </span>
  );
}
